services:
  reservations_back_service:
    container_name: 'reservations_back'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env

networks:
  myNetwork:
    external: true