services:
  reservations_back_service:
    container_name: 'reservations_back'
    build:
      context: .
    ports:
      - "7777:8000"
    networks:
      - myNetwork
    env_file:
      - .env


networks:
  myNetwork:
    external: true